import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Bot, Cpu, Shield, Zap, BarChart3, FileSearch } from "lucide-react";

const About = () => {
  const features = [
    {
      icon: Bot,
      title: "Advanced AI Detection",
      description: "Our system can identify content generated by ChatGPT, Claude, Gemini, Gamma.app, Beautiful.ai, Tome, and more."
    },
    {
      icon: Cpu,
      title: "Deep Learning Models",
      description: "Trained on millions of documents to recognize subtle patterns that distinguish AI-generated content from human writing."
    },
    {
      icon: FileSearch,
      title: "Full Content Extraction",
      description: "Extracts and analyzes every slide, page, and speaker note from your presentations for comprehensive analysis."
    },
    {
      icon: BarChart3,
      title: "Detailed Analytics",
      description: "Get detailed breakdowns including NLP analysis, metadata inspection, design patterns, and plagiarism detection."
    },
    {
      icon: Shield,
      title: "Privacy First",
      description: "Your documents are processed securely and never stored. Analysis happens in real-time with no data retention."
    },
    {
      icon: Zap,
      title: "Lightning Fast",
      description: "Get comprehensive results in seconds, not minutes. Our optimized pipeline delivers instant insights."
    }
  ];

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Header />
      <main className="flex-1 pt-24 pb-16">
        <div className="container mx-auto px-4">
          {/* Hero Section */}
          <div className="text-center max-w-3xl mx-auto mb-16">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-card border border-border/50 shadow-sm mb-6">
              <Bot className="w-4 h-4 text-primary" />
              <span className="text-sm font-medium text-foreground/80">About GenCheck</span>
            </div>
            <h1 className="text-4xl md:text-5xl font-extrabold gradient-text mb-6">
              Powerful AI Detection Technology
            </h1>
            <p className="text-lg text-muted-foreground">
              GenCheck uses state-of-the-art machine learning algorithms to analyze presentations 
              and documents, providing accurate detection of AI-generated content with detailed 
              breakdowns of writing patterns, structural elements, and tool signatures.
            </p>
          </div>

          {/* Features Grid */}
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-16">
            {features.map((feature, index) => (
              <div key={index} className="feature-card group">
                <div className="w-12 h-12 bg-feature-icon rounded-xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                  <feature.icon className="w-6 h-6 text-primary" />
                </div>
                <h3 className="text-lg font-semibold text-foreground mb-2">{feature.title}</h3>
                <p className="text-muted-foreground text-sm">{feature.description}</p>
              </div>
            ))}
          </div>

          {/* How It Works */}
          <div className="bg-card rounded-2xl border border-border p-8 md:p-12">
            <h2 className="text-2xl font-bold text-foreground text-center mb-8">How It Works</h2>
            <div className="grid md:grid-cols-3 gap-8">
              <div className="text-center">
                <div className="w-16 h-16 gradient-bg rounded-2xl flex items-center justify-center mx-auto mb-4">
                  <span className="text-2xl font-bold text-white">1</span>
                </div>
                <h3 className="font-semibold text-foreground mb-2">Upload Your File</h3>
                <p className="text-sm text-muted-foreground">
                  Upload any PowerPoint (.pptx) or PDF file up to 50MB in size.
                </p>
              </div>
              <div className="text-center">
                <div className="w-16 h-16 gradient-bg rounded-2xl flex items-center justify-center mx-auto mb-4">
                  <span className="text-2xl font-bold text-white">2</span>
                </div>
                <h3 className="font-semibold text-foreground mb-2">AI Analysis</h3>
                <p className="text-sm text-muted-foreground">
                  Our AI extracts content, analyzes patterns, and detects AI signatures.
                </p>
              </div>
              <div className="text-center">
                <div className="w-16 h-16 gradient-bg rounded-2xl flex items-center justify-center mx-auto mb-4">
                  <span className="text-2xl font-bold text-white">3</span>
                </div>
                <h3 className="font-semibold text-foreground mb-2">Get Results</h3>
                <p className="text-sm text-muted-foreground">
                  Receive detailed reports with AI probability scores and tool detection.
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default About;
